### ISSUE TITLE
Cannot add NuGet package to a .NET project

### ISSUE THREAD

**Issue by jandic** [AmpScm/SharpProj#9]
Hi,

I would like to test this project as an alternative to ProjNet. It looks quite impressing. However, I don't seem to be able to add SharpProj NuGet package to any .NET project. I tried a couple of versions of .NET Framework but it always gives me the following error message:

Could not install package 'SharpProj.Core 8.1.26'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

I tried .NET Framework 4.5, 4.6, 4.7.2 and 4.8. I also tried .NET 5 but no luck. Can you please advise what .NET Framework is the package set up with? I checked the .DLL in the package and it seems to be built for .NET Framework 4.6 but adding it via NuGet still fails.

Thanks,
Pavel

**Comment by rhuijben** [comment]
This should have been fixed with the more recent packages. There are now multiple components with different handling in the single nuget package. I would recomment using <PackageReference /> in your project, as in that case the right component should automatically be selected (win32-net, x64-net, win32-core, x64-core are all included now)
